import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import { ToastContainer, toast } from 'react-toastify';
import { Nunito} from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "react-hot-toast";
import ClientOnly from "./components/ClientOnly";
import { Providers } from "./components/Sessionprovider";

export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <ToastContainer
      
      ></ToastContainer>
    <Providers>

      <body className={inter.className} >
        <Toaster position="top-center"></Toaster>
        <Suspense fallback={<div>Loading content...</div>}>
        {children}
        </Suspense>
        </body>
    </Providers>
     

    </html>
  );
}
