

import { Toaster } from "@/components/ui/toaster"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import { Poppins } from "next/font/google";
import { ToastContainer, toast } from 'react-toastify';
import { Nunito} from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import ClipLoader from "react-spinners/ClipLoader";
import ClientOnly from "./components/ClientOnly";
import { Providers } from "./components/Sessionprovider";

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import { UserProviders } from "./components/UserProvider";
const poppinsinit=Poppins({
  subsets:['latin'],
  display:'swap',
  variable:'--font-poppins',
  weight:['300','600','100','200','400','500','700','800']
})

export const metadata: Metadata = {
  title: "Airbnb",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {





  return (
    
<ClerkProvider>
      <Providers>
        <html lang="en">
          
          <body className={`${inter.className} ${poppinsinit.variable}` }>
     
<div className="poppins">

            <UserProviders>
              {/* Toast Container for notifications */}

              {/* Suspense fallback to show loading state */}
              <Suspense fallback={<div className=" text-red-600 w-screen h-screen flex justify-center items-center"></div>}>
              

                {children}
              </Suspense>

              {/* Toaster for hot toast notifications */}
            </UserProviders>
                <Toaster />
</div>
           
          </body>
           
        </html>
      </Providers>
    </ClerkProvider>
  );
}
